# Generated by Django 4.2.9 on 2024-02-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_raw', models.CharField(blank=True, max_length=200, null=True)),
                ('message_with_ents', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, max_length=200, null=True)),
                ('tokens', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('tokens_len', models.CharField(blank=True, max_length=200, null=True)),
                ('host_sender', models.CharField(blank=True, max_length=200, null=True)),
                ('host_receiver', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_sender', models.CharField(blank=True, max_length=200, null=True)),
                ('ip_receiver', models.CharField(blank=True, max_length=200, null=True)),
                ('start_processing', models.CharField(blank=True, max_length=200, null=True)),
                ('finish_processing', models.CharField(blank=True, max_length=200, null=True)),
                ('time_processing', models.CharField(blank=True, max_length=200, null=True)),
                ('ents_posi', models.CharField(blank=True, max_length=200, null=True)),
                ('ents_text', models.CharField(blank=True, max_length=200, null=True)),
                ('ents_kind', models.CharField(blank=True, max_length=200, null=True)),
                ('sentence_size', models.CharField(blank=True, max_length=200, null=True)),
                ('sentence_list', models.CharField(blank=True, max_length=200, null=True)),
                ('tot_noun', models.CharField(blank=True, max_length=200, null=True)),
                ('tot_pron', models.CharField(blank=True, max_length=200, null=True)),
                ('tot_punc', models.CharField(blank=True, max_length=200, null=True)),
                ('tot_conj', models.CharField(blank=True, max_length=200, null=True)),
                ('tot_num', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_noun', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_verb', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_adve', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_pron', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_adje', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_punc', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_conj', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_det', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_num', models.CharField(blank=True, max_length=200, null=True)),
                ('lst_other', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
