# Generated by Django 4.2.9 on 2024-02-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
