# Generated by Django 4.2.9 on 2024-01-13 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendc2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communication',
            name='user',
        ),
    ]
